### ISSUE TITLE
Compiled module failing to install

### ISSUE THREAD

**Issue by OwOAudrey** [SJWsAreACancer/FontChanger#1]
After compiling the module, and trying to install it, im greeted with a failed installation and the following error log
- Copying zip to temp directory
- Installing Fontchanger-2.8.0.1-08.15.2020.zip
- Device is system-as-root
Archive:  /data/user/0/com.clVfr.X.R.MrbF.Z/cache/flash/install.zip
  inflating: module.prop
--
 Font Changer 
 by John Fawkes 
--
Archive:  /data/user/0/com.clVfr.X.R.MrbF.Z/cache/flash/install.zip
  inflating: customize.sh
--
 Powered by Magisk 
--
Archive:  /data/user/0/com.clVfr.X.R.MrbF.Z/cache/flash/install.zip
  inflating: module.prop
Checking for any other font modules installed... 
 [-] Extracting module files [-] 
Archive:  /data/user/0/com.clVfr.X.R.MrbF.Z/cache/flash/install.zip
  inflating: README.md
Archive:  /data/user/0/com.clVfr.X.R.MrbF.Z/cache/flash/install.zip
   creating: tools/
  inflating: tools/bash-arm
  inflating: tools/bash-x86
  inflating: tools/busybox-arm
  inflating: tools/curl-x86
  inflating: tools/sleep-x86
  inflating: tools/curl-arm
  inflating: tools/zip-arm
  inflating: tools/sleep-arm
  inflating: tools/busybox-x86
  inflating: tools/zip-x86
 [-] Checking For Internet Connection... [-] 
 [-] Testing internet connection [-] 
 [-] All Lists Downloaded Successfully... [-] 
+ true
+ echo 'Busybox Already Installed'
Busybox Already Installed
 - Downloading needed files

! Installation failed

**Comment by SJWsAreACancer** [comment]
He must have put a block on the files needed to be downloaded. I will try to get them and rehost.

**Comment by OwOAudrey** [comment]
> He must have put a block on the files needed to be downloaded. I will try to get them and rehost.

i found some here, however im fairly certain these dont match the version here
[https://github.com/unixandria-xda/fontchanger-scripts](url)

**Comment by SJWsAreACancer** [comment]
Most Fonts dont get updated. what you see is what will always be, however he did add MORE fonts and emojis, but I will take what is listed and get to work.

**Comment by OwOAudrey** [comment]
> Most Fonts dont get updated. what you see is what will always be, however he did add MORE fonts and emojis, but I will take what is listed and get to work.

Many thanks.

**Comment by SJWsAreACancer** [comment]
Grim#1806 on Discord.
